export { default as Navbar } from './navbar/Navbar';
export { default as Footer } from './footer/Footer';
export { default as Featured } from './featured/Featured';
export { default as Features } from './features/Features';
export { default as Business } from './business/Business';
export { default as TrustedBy } from './trusted-by/TrustedBy';
export { default as Slide } from './slide/Slide';
export { default as CategoryCard } from './category-card/CategoryCard';
export { default as ProjectCard } from './project-card/ProjectCard';
